server:
  port: 8080

redis:
  addr: localhost:6379
  password: ""

asynq:
  concurrency: 10

registries:
  src:
    url: localhost:5001
    username: ""
    password: ""
  dst:
    url: localhost:5002
    username: ""
    password: ""
